# Generated by Django 5.0.2 on 2024-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_units', models.IntegerField()),
            ],
        ),
    ]
