# Generated by Django 5.1.2 on 2024-10-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_tenant_unit_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
